### ISSUE TITLE
New logo for Girinoscope

### ISSUE THREAD

**Issue by reallinfo** [Chatanga/Girinoscope#1]
I wanted to contribute to Girinoscope. I designed a logo for Girinoscope. If you like it, I'll send you the files.

![girinoscope](https://user-images.githubusercontent.com/36298335/37919484-ae5c559e-312c-11e8-8021-0beec45650a0.jpg)

**Comment by Chatanga** [comment]
Thank for this nice logo! I will have some changes to commit soon and I will take this opportunity to include your icon with it. Unfortunately, Java Swing (JavaFX doesn't fare better actually) doesn't handle application icons very well and the end result is usually blurry on most desktop environments.

**Comment by reallinfo** [comment]
Hello @Chatanga. I'm glad you like it. What kind of logo can I design for you? do you want a square logo for the desktop?
