### ISSUE TITLE
No Girino detected on <appropriate device path>

### ISSUE THREAD

**Issue by DGxInfinitY** [Chatanga/Girinoscope#2]
I have installed Girino on an Arduino UNO and it still appears to not detect it? I've done the necessary code changes and I can't get any readings.

**Comment by Chatanga** [comment]
That could be a lot of things, but let see if we can narrow down the possibilities. First:
1) What is the version of Girinoscope you are using (the version is displayed in the About menu)?
2) What is your OS?

**Comment by DGxInfinitY** [comment]
I am using Version 1.1.4 of Girinoscope and I am running Oracle Java 8 on ElementaryOS(based on Ubuntu 16.04) running the latest mainline kernel.

**Comment by Chatanga** [comment]
The actual, unreleased version, is 1.2.0-SNAPSHOT. You could build it locally, it is worth it ;). That being said, the 1.1.4 should work without problems. Is your user part of the "dialout" group?

	$ id

If not, you could add it this way:

	$ sudo usermod -a -G dialout $USER

Then logout/login before retrying.

**Comment by DGxInfinitY** [comment]
Yes I am added to the dialout group(the arduino needed to be loaded with Girino) I would build from source however I am quite incompetent with Java applications and don't quite know how to build from source. I have downloaded the source tho so I might look into it.

**Comment by Chatanga** [comment]
I’ve just pushed a fix regarding serial reconnection after a failure. It doesn’t address your problem, but the UI should behave in a nicer way when failing to connect to Girino.

Regarding you problem, could you try to reset your Girino right after starting to acquire the signal? Maybe the reset on DTR is not happening here.
